deployment:
  tasks:
    - export DEPLOYPATH=/home/synd/public_html/
    - /usr/bin/rsync -av --delete --exclude='.git' --exclude='.cpanel.yml' --exclude='.htaccess' --exclude='uploads' ./ $DEPLOYPATH
